use_frameworks!

platform :ios, '8.0'

target 'ProatomicCocoalumberjackLogger_Example' do
  pod 'ProatomicCocoalumberjackLogger', :path => '../'

  target 'ProatomicCocoalumberjackLogger_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
